Added slide expiration date
PrestaShop/ps_imageslider pull request #59
Opened 2021-03-03 00:20 UTC by alfonsolr09

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Sometimes we forget about expired slides on our store. This will help to prevent unwanted old slider banners.
| Type?         | new feature 
| BC breaks?    |  no
| Fixed ticket? | https://github.com/PrestaShop/ps_imageslider/pull/42#issuecomment-606477725,    #40, #41, #42.
| How to test?  | I copied the pr from @PrestaShark , since he didn't

See this https://github.com/PrestaShop/ps_imageslider/pull/42#issuecomment-606477725

2021-03-03 10:31 UTC, PierreRambaud commented
Hey I think it's a good idea, but could you please create an issue on https://github.com/PrestaShop/PrestaShop/issues/new/choose
IN order to be sure the behavior is ok :)

2021-03-03 12:29 UTC, kpodemski requested changes
Hey! Great idea.

Few things:
- it would be better to have possibility to use hours and minutes too, full date time
- make sure to add proper field to `renderForm` as we cannot edit `expiration` right now
- make sure to move logic outside `view`

2021-03-03 12:29 UTC, kpodemski commented on views/templates/hook/list.tpl
> +								{if $slide.expiration|date_format:'%Y-%m-%d' >= $smarty.now|date_format:'%Y-%m-%d' }<span style="color:green">{$slide.expiration}</span>{else}<span style="color:red">{$slide.expiration}</span
Please use `callback` and leave view without this kind of logic

2021-03-03 12:29 UTC, kpodemski commented on views/templates/hook/slider.tpl
> +        {if $slide.active AND $slide.expiration|date_format:'%Y-%m-%d' >= $smarty.now|date_format:'%Y-%m-%d'}
Please move this logic into module core

2021-03-03 12:39 UTC, alfonsolr09 commented
> ¡Oye! Gran idea.
> 
> Pocas cosas:
> 
> * Sería mejor tener la posibilidad de usar horas y minutos también, fecha completa
> * asegúrese de agregar el campo adecuado, `renderForm`ya que no podemos editar en `expiration`este momento
> * asegúrate de mover la lógica afuera `view`

you can do it

2021-04-09 23:47 UTC, alfonsolr09 commented
@kpodemski I do not know how to do that, can you do it?

2021-04-12 09:40 UTC, kpodemski commented
@alfonsolr09 I don't have time now, but I'll bookmark this PR so I can get back to it later

2021-08-13 21:18 UTC, alfonsolr09 commented
hello, could you do it? @kpodemski

2021-10-05 14:21 UTC, PierreRambaud commented
ping @kpodemski are you able to do it? :D

2021-10-06 06:03 UTC, kpodemski commented
Hello @alfonsolr09 

We can think about this in the future versions of the `ps_imageslider` module. Right now, the core team doesn't have time to finish this PR.

2021-10-06 10:53 UTC, PierreRambaud commented
> @PierreRambaud no, this module needs to be refactored anyway :(
> 
> Btw. if you're here, give me access to this repo, please heart

Done

2021-12-13 16:36 UTC, PierreRambaud commented
Hi @alfonsolr09 ,

Since there is no activity for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-12-13 16:36 UTC, closed without merging