(ps_imaslider install/reset) fix position to the top for hook display…
PrestaShop/ps_imageslider pull request #60
Opened 2021-03-19 09:31 UTC by Mch0

…Home

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | on reset or uninstall then install, modules are hooked in the wrong place
| Type?         | bug fix 
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | Fixes PrestaShop/Prestashop#20748
| How to test?  | Steps to Reproduce
Steps to reproduce the behavior:

Go to BO > Module Manager page > Search for the slider module
Click on reset
Go to FO > Home page
See error => the slider is at the last position on the home page

2021-03-19 09:34 UTC, Progi1984 commented on ps_imageslider.php
> +            //Fix slider position to the top
```suggestion
            // Set slider position to the top
```

2021-03-19 09:34 UTC, Progi1984 approved these changes

2021-03-19 09:57 UTC, PierreRambaud requested changes
I'm not sure it's a bug :thinking: You reset or reinstall a module, the position is automatically set at the end, nothing mean when you install/reset these modules your theme want to be set at position X.

You've access to the Module Positions page to change the value.

2021-03-26 09:02 UTC, matthieu-rolland commented
@PrestaShop/product-team do you have an opinion regarding this issue or should we both close the issue and the PR ?

2021-03-26 09:43 UTC, Mch0 commented
For this PR can be usefull because the slider image block on website are always on the top, there are very few websites to my knowledge who put a banner slider at third position

2021-03-26 09:52 UTC, NeOMakinG commented
> I'm not sure it's a bug 🤔 You reset or reinstall a module, the position is automatically set at the end, nothing mean when you install/reset these modules your theme want to be set at position X.
> 
> You've access to the Module Positions page to change the value.

I agree with @Mch0, when you first install a shop wich classic, it's on the top, when you reset or install again the module, you expect to have it on the same hook

2021-03-26 10:20 UTC, PierreRambaud commented
> > I'm not sure it's a bug thinking You reset or reinstall a module, the position is automatically set at the end, nothing mean when you install/reset these modules your theme want to be set at position X.
> > You've access to the Module Positions page to change the value.
> 
> I agree with @Mch0, when you first install a shop wich classic, it's on the top, when you reset or install again the module, you expect to have it on the same hook

You expect to have the same block on reset maybe, but not on install, the position is not fixed, if you do it, it will be done for all themes. There is a page that's here for this purpose => Modules position

2021-03-26 16:11 UTC, NeOMakinG commented
> > > I'm not sure it's a bug thinking You reset or reinstall a module, the position is automatically set at the end, nothing mean when you install/reset these modules your theme want to be set at position X.
> > > You've access to the Module Positions page to change the value.
> > 
> > 
> > I agree with @Mch0, when you first install a shop wich classic, it's on the top, when you reset or install again the module, you expect to have it on the same hook
> 
> You expect to have the same block on reset maybe, but not on install, the position is not fixed, if you do it, it will be done for all themes. There is a page that's here for this purpose => Modules position

Oh, I managed to understand what you wanted to say and I feel like you're right

2021-06-23 12:50 UTC, matthieu-rolland reviewed
so I guess this PR can be closed

2021-06-23 13:14 UTC, closed without merging